import Link from "next/link";
import { Check } from "lucide-react";
import { Button } from "@/components/ui/button";

const features = ["PDF contract tracking", "Source-backed renewal extraction", "Human confirmation", "Escape Windows", "Owner assignment", "Renew / Renegotiate / Cancel tracking"];

export function PricingSection() {
  return <section id="pricing" className="border-b border-line py-24 sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8"><div><h2 className="max-w-2xl text-balance text-3xl font-semibold tracking-[-0.05em] sm:text-5xl">Start with the renewals that can still be changed.</h2><p className="mt-6 max-w-xl text-pretty leading-7 text-muted-ink">One focused plan for founder-led, finance, operations and procurement teams that need cancel-by dates visible before another commitment starts.</p><p className="mt-8 max-w-lg border-l-2 border-acid pl-4 text-sm leading-6 text-muted-ink">Checkout is not enabled yet. The current product remains a launch preview while billing is finalized.</p></div><div className="border border-[#cbd5ce] bg-white p-6 shadow-[0_18px_50px_rgba(18,33,29,.07)] sm:p-8"><div className="flex flex-col gap-6 border-b border-line pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-muted-ink">Team</p><p className="mt-2 text-5xl font-semibold tracking-[-0.055em] tabular-nums">$49<span className="ml-1 text-sm font-medium tracking-normal text-muted-ink">/ month</span></p></div><p className="max-w-xs text-sm leading-6 text-muted-ink">Focused vendor-renewal control without a full CLM rollout.</p></div><ul className="mt-7 grid gap-3 sm:grid-cols-2">{features.map((feature) => <li key={feature} className="flex items-start gap-2 text-sm"><Check aria-hidden="true" size={16} className="mt-0.5 shrink-0 text-positive" />{feature}</li>)}</ul><Button asChild className="mt-8 w-full" size="lg"><Link href="/sign-in?next=/app/upload">Start Free</Link></Button></div></div></section>;
}
