import Link from "next/link";
import { Check } from "lucide-react";
import { Button } from "@/components/ui/button";

const features = ["Contract tracking", "Renewal-term review", "Escape Windows", "Owner assignment", "Decision history", "Renewal reminders"];

export function PricingSection() {
  return <section id="pricing" className="border-b border-[#dfe4df] py-20 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#3e7163]">Pricing</p><h2 className="mt-4 text-balance text-3xl font-semibold tracking-[-0.045em] sm:text-4xl">Simple enough to start before the next renewal.</h2><p className="mt-4 text-pretty leading-7 text-[#65716b]">A focused plan for founder-led, finance, operations and procurement teams that need the renewal decision visible.</p></div><div className="mx-auto mt-10 max-w-md rounded-xl border border-[#cfd8d1] bg-white p-6 shadow-[0_14px_40px_rgba(18,33,29,.06)] sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold">Team</p><p className="mt-1 text-sm text-[#6a756f]">Vendor renewal control</p></div><span className="rounded-md bg-[#eff4ef] px-2 py-1 text-xs font-semibold text-[#315f52]">Launch plan</span></div><p className="mt-6 text-4xl font-semibold tracking-[-0.045em] tabular-nums">$49<span className="text-sm font-medium tracking-normal text-[#6d7872]"> / month</span></p><p className="mt-3 text-sm leading-6 text-[#68736d]">Track vendor agreements, protect cancel-by dates and keep renewal decisions owned.</p><ul className="mt-6 grid gap-3">{features.map((feature) => <li key={feature} className="flex items-center gap-2 text-sm"><Check aria-hidden="true" size={16} className="text-positive" />{feature}</li>)}</ul><Button asChild className="mt-7 w-full" size="lg"><Link href="/app/upload">Start Free</Link></Button><p className="mt-3 text-center text-xs leading-5 text-[#7a8580]">Product preview · Checkout is not enabled yet.</p></div></div></section>;
}
